#! /bin/bash

source ./config/playground.env

set -e
trap 'echo "$(date +%H:%M:%S) | Stopping..." >> $1; exit 0' SIGTERM

echo "$(date +%H:%M:%S) | Starting..." >> $1

ELAPSED_TIME=$((60*60))     # 60 minutes
while true; do
    shopt -s nullglob
    for file in "$LOG_DIR"/*.log.gz; do
        now=$(date +%s)
        file_age=$(stat -c %W $file)

        if [ $((now-file_age)) -gt $ELAPSED_TIME ]; then
            rm $file
            echo "$(date +%H:%M:%S) | Cleaning up... (Removed $(basename "$file"))" >> $1
        fi
    done
    shopt -u nullglob
    sleep 60
done