#! /bin/bash

source ./config/playground.env

set -e
trap 'echo "$(date +%H:%M:%S) | Stopping..." >> "$1"; exit 0' SIGTERM

echo "$(date +%H:%M:%S) | Starting..." >> "$1"

MAX_SIZE=100000

while true; do
    for file in "$LOG_DIR"/*.log; do

        [[ "$file" =~ \.[0-9]{14}\.log$ ]] && continue
        [[ "$file" =~ \.gz$ ]] && continue

        FILENAME=$(basename $file .log)
        FILESIZE=$(stat -c%s "$file" | tr -d '[:space:]')
        
        if (( FILESIZE > MAX_SIZE )); then
            timestamp=$(date +%Y%m%d%H%M%S)
            rotated="$LOG_DIR/${FILENAME}_$timestamp.log"
            mv "$file" "$rotated"
            gzip "$rotated"
            echo "$(date +%H:%M:%S) | Zipped $FILENAME ($FILESIZE bytes)" >> "$1"
            touch "$file"
        fi
    done
    sleep 60
done